services:

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html

  database:
    build:
      dockerfile: docker/database/Dockerfile
    ports:
      - "3306:3306"