services:
  nginx:
    image: registry.digitalocean.com/webdevwithmatt/webserver-alpine:latest
    restart: always
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/ping"]
      interval: 60s
      timeout: 3s
      retries: 3

  php:
    image: registry.digitalocean.com/webdevwithmatt/php-runtime-alpine:latest
    restart: always
    expose:
      - 9000
    volumes:
      - composer_dependencies:/var/www/html/vendor

  database:
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
