<?php $this->headTitle('Home'); ?>

<div class="row">
    <div class="col-md-12">
        <h1>Hawaii 5-0 Main Cast 2010 - 2020</h1>
        <table class="table table-striped table-hover table-bordered table-sm">
            <thead class="table-dark">
            <tr>
                <th>id</th>
                <th>first name</th>
                <th>last name</th>
                <th>email address</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->stmt as $row): ?>
                <tr>
                    <td><?= $row['id'] ?></td>
                    <td><?= $row['first_name'] ?></td>
                    <td><?= $row['last_name'] ?></td>
                    <td><a href="mailto:<?= $row['email_address'] ?>"><?= $row['email_address'] ?></a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
